apiVersion: batch/v1
kind: Job
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      restartPolicy: Never
      containers:
        - name: ingestion-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: CLICKHOUSE_HOST
              value: {{ .Values.env.clickhouseHost }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.env.clickhouseUser }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}