apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingestion-service
  namespace: observability
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ingestion-service
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
