alloy:
  configMap:
    alloy.yaml: |
      server:
        log_level: info
        http_listen_address: 0.0.0.0
        http_listen_port: 12345

      discovery.kubernetes:
        - role: node
        - role: pod
        - role: service

      prometheus.scrape:
        - targets:
            - localhost:9100
          job_name: "node_exporter"

      prometheus.remote_write:
        - endpoint: http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write
