replicaCount: 1

image:
  repository: ghcr.io/florita1/ingestion-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  clickhouseHost: clickhouse.clickhouse.svc.cluster.local
  clickhouseUser: default

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi