apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  configuration:
    users:
      terraform/password: terraformpass123
      terraform/profile: default
      terraform/quota: default
      terraform/networks/ip.1: "::1"
      terraform/networks/ip.2: "127.0.0.1"
      terraform/networks/ip.3: "10.0.0.0/8"
      terraform/grants/query: |
        GRANT ALL ON *.* TO terraform WITH GRANT OPTION

    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
        services:
          - name: clickhouse
            port: 8123
            protocol: HTTP
            template: default
            spec:
              type: LoadBalancer
