apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  configuration:
    users:
      terraform/password: terraformpass123
      terraform/networks/ip: "::/0"
      terraform/profile: default
      terraform/quota: default
      terraform/grants: |
        GRANT CREATE DATABASE, CREATE TABLE, INSERT, SELECT, ALTER, DROP, SHOW, SYSTEM, ACCESS MANAGEMENT ON *.* TO terraform WITH GRANT OPTION

    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
        services:
          - name: clickhouse
            port: 8123
            protocol: HTTP
            template: default
            spec:
              type: LoadBalancer
