apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  configuration:
    users:
      terraform/password: terraformpass123

    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
        services:
          - name: clickhouse
            port: 8123
            protocol: HTTP
            template: default
            spec:
              type: LoadBalancer
