config:
  clients:
    - url: http://loki:3100/loki/api/v1/push

  snippets:
    pipeline_stages:
      - cri: {}
      - labeldrop:
          - filename

    extraScrapeConfigs: |
      - job_name: ingestion-logs
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ingestion
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)

rbac:
  create: true

serviceAccount:
  create: true

serviceMonitor:
  enabled: false
