users:
  default/password: mysecuredefaultpass

  terraform/password: terraformpass123
  terraform/profile: default
  terraform/quota: default

defaults:
  templates:
    podTemplate: clickhouse-default-pod-template
    dataVolumeClaimTemplate: clickhouse-default-volume-template

templates:
  podTemplates:
    - name: clickhouse-default-pod-template
      podDistribution:
        - type: "Shard"
      spec:
        containers:
          - name: clickhouse
            image: clickhouse/clickhouse-server:23.8
            ports:
              - containerPort: 8123
                name: http
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"

  dataVolumeClaimTemplates:
    - name: clickhouse-default-volume-template
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

clusters:
  - name: clickhouse
    layout:
      shardsCount: 1
      replicasCount: 1
    templates:
      podTemplate: clickhouse-default-pod-template
      dataVolumeClaimTemplate: clickhouse-default-volume-template
    services:
      - name: clickhouse
        port: 8123
        protocol: HTTP
        template: default
        spec:
          type: LoadBalancer
