auth:
  enabled: true
  username: default
  password: clickhouse

image:
  repository: docker.io/bitnami/clickhouse
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: tcp
      port: 9000
      targetPort: tcp

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: false
