replicaCount: 1

image:
  repository: clickhouse/clickhouse-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8123

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: false