auth:
  enabled: true
  username: default
  password: clickhouse

image:
  repository: docker.io/bitnami/clickhouse
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    http: 8123
    tcp: 9000

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: false
