deploymentMode: SingleBinary

global:
  priorityClassName: ""
  registry: ""
  image: {}

loki:
  target: single-process
  image:
    repository: grafana/loki
    tag: main-ccb54c5
    pullPolicy: IfNotPresent
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  limits_config:
    retention_period: 168h # 7 days
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
  configObjectName: loki-config

singleBinary:
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 5
    timeoutSeconds: 1
  automountServiceAccountToken: true
  replicas: 1
  persistence:
    enabled: false
  service: {}
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  terminationGracePeriodSeconds: 30

serviceMonitor:
  enabled: true

# Disable unnecessary components
test:
  enabled: false

gateway:
  enabled: false

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

enterprise:
  enabled: false

serviceAccount:
  create: true
  name: ""

sidecar:
  rules:
    enabled: false

rbac:
  pspEnabled: false

securityContext: {}
