deploymentMode: SingleBinary

loki:
  image:
    repository: grafana/loki
    tag: main-ccb54c5
    pullPolicy: IfNotPresent
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  limits_config:
    retention_period: 168h # 7 days

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: gp2
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

serviceMonitor:
  enabled: true

# Disable unnecessary components
test:
  enabled: false

gateway:
  enabled: false

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

enterprise:
  enabled: false

serviceAccount:
  create: true
  name: ""
