configMap:
  create: true
  alloy.yaml: |
    otelcol.receiver.otlp "default" {
      protocols = ["http"]
    }

    otelcol.exporter.otlphttp "tempo" {
      endpoint = "http://tempo.observability.svc.cluster.local:4318"
      tls {
        insecure = true
      }
    }

    otelcol.processor.batch "default" {}

    otelcol.service "default" {
      pipelines = {
        traces = {
          receivers  = [otelcol.receiver.otlp.default]
          processors = [otelcol.processor.batch.default]
          exporters  = [otelcol.exporter.otlphttp.tempo]
        }
      }
    }

service:
  extraPorts:
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
