apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  project: default
  source:
    repoURL: https://github.com/florita1/clickhouse-observability-platform.git
    targetRevision: HEAD
    path: k8s/clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
