apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.1.2
    helm:
      values: |
        configMap:
          create: true
          alloy.yaml: |
            server "default" {
              http_listen_address = "0.0.0.0"
              http_listen_port    = 12345
            }

            otelcol.receiver.otlp "default" {
              protocols = ["http", "grpc"]
            }

            otelcol.processor.batch "default" {}

            otelcol.exporter.otlphttp "tempo" {
              endpoint = "http://tempo.observability.svc.cluster.local:4318"
              tls {
                insecure = true
              }
            }

            otelcol.service "default" {
              pipelines = {
                traces = {
                  receivers  = [otelcol.receiver.otlp.default]
                  processors = [otelcol.processor.batch.default]
                  exporters  = [otelcol.exporter.otlphttp.tempo]
                }
              }
            }

        service:
          extraPorts:
            - name: otlp-http
              port: 4318
              targetPort: 4318
              protocol: TCP
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
