apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.2.0
    helm:
      values: |
        alloy:
          configMap:
            content: |
              otelcol.receiver.otlp "default" {
                protocols = ["http", "grpc"]
              }

              otelcol.exporter.otlphttp "tempo" {
                endpoint = "http://tempo.observability.svc.cluster.local:4318"
                tls {
                  insecure = true
                }
              }

              otelcol.processor.batch "default" {}

              otelcol.service "default" {
                pipelines = {
                  traces = {
                    receivers  = [otelcol.receiver.otlp.default],
                    processors = [otelcol.processor.batch.default],
                    exporters  = [otelcol.exporter.otlphttp.tempo],
                  },
                }
              }
          extraPorts:
            - name: otlp-http
              port: 4318
              targetPort: 4318
              protocol: TCP
            - name: otlp-grpc
              port: 4317
              targetPort: 4317
              protocol: TCP

        service:
          enabled: true
          type: ClusterIP
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
