apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.1.2
    helm:
      values: |
        service:
          extraPorts:
            - name: otlp-http
              port: 4318
              targetPort: 4318
              protocol: TCP

        configMap:
          create: true
          alloy.yaml: |
            server:
              log_level: info
              http_listen_address: 0.0.0.0
              http_listen_port: 12345

            discovery.kubernetes:
              - role: node
              - role: pod
              - role: service

            prometheus.scrape:
              - targets:
                  - localhost:9100
                job_name: "node_exporter"

            prometheus.remote_write:
              - endpoint: http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write

            otelcol.receiver.otlp:
              protocols:
                http:
                grpc:

            otelcol.exporter.otlphttp:
              endpoint: http://tempo.observability.svc.cluster.local:4318
              tls:
                insecure: true

            otelcol.processor.batch: {}

            otelcol.service:
              pipelines:
                traces:
                  receivers: [otlp]
                  processors: [batch]
                  exporters: [otlphttp]
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
