apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.2.0
    helm:
      valueFiles:
        - apps/alloy-values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
