apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.2.0
    helm:
      values: |
        alloy:
          configMap:
            content: |
              otelcol.receiver.otlp "default" {
                grpc {
                  endpoint = "0.0.0.0:4317"
                }
                http {
                  endpoint = "0.0.0.0:4318"
                }
                output {
                  traces = [otelcol.processor.batch.default.input]
                }
              }

              otelcol.processor.batch "default" {
                output {
                  traces = [otelcol.exporter.otlp.tempo.input]
                }
              }

              otelcol.exporter.otlp "tempo" {
                client {
                  endpoint = "http://tempo.observability.svc.cluster.local:4317"
                  tls {
                    insecure = true
                  }
                }
              }

          extraPorts:
            - name: otlp-grpc
              port: 4317
              targetPort: 4317
            - name: otlp-http
              port: 4318
              targetPort: 4318

        service:
          enabled: true
          type: ClusterIP
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
