apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: 'https://github.com/florita1/clickhouse-observability-platform.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - alloy-values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
