apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.2.0
      helm:
        valueFiles:
          - ../values.yaml  # relative path from chart to the next source’s file
    - repoURL: https://github.com/florita1/clickhouse-observability-platform.git
      targetRevision: HEAD
      ref: values
      path: apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
