apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pixie
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://pixie-operator-charts.storage.googleapis.com/
    chart: pixie-operator-chart
    targetRevision: 0.0.11
    helm:
      values: |
        clusterName: clickhouse-observability-cluster
        cloudAddr: getcosmic.ai:443

        pemResources:
          requests:
            memory: 2Gi
          limits:
            memory: 2Gi

        pemAffinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchFields:
                    - key: metadata.name
                      operator: In
                      values:
                        - ip-10-0-1-34.ec2.internal

        pemTolerations:
          - key: node.kubernetes.io/not-ready
            operator: Exists
            effect: NoExecute
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
          - key: node.kubernetes.io/disk-pressure
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/memory-pressure
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/pid-pressure
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/unschedulable
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/network-unavailable
            operator: Exists
            effect: NoSchedule
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
