apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.23.2
    helm:
      releaseName: tempo
      values: |
        persistence:
          enabled: false
        tempo:
          storage:
            trace:
              backend: local
       service:
          type: ClusterIP
          ports:
            - name: http
              port: 3100
              targetPort: 3100
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
