apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-users-config
  namespace: clickhouse
data:
  users.xml: |
    <yandex>
      <users>
        <default>
          <password_sha256_hex>8387e15c17bfe73e58d0e1c0592ae5a4e0a9e3fc6c57d093656f53ae3d75b8da</password_sha256_hex>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </default>
      </users>
    </yandex>
