apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-users-config
  namespace: clickhouse
data:
  users.xml: |
    <yandex>
      <users>
        <default>
          <password_sha256_hex>$(echo -n 'clickhouse' | sha256sum | awk '{print $1}')</password_sha256_hex>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </default>
      </users>
    </yandex>
