configs:
  params:
    server.insecure: true  # Allows access without TLS (good for local dev)

server:
  service:
    type: LoadBalancer  # Or use ClusterIP if using port-forward
  containerPorts:
    http: 8080
    metrics: 8083
