name: Terraform CI

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Format & Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Set up Terraform variables
        run: |
          echo "TF_VAR_clickhouse_admin_password=${{ secrets.CLICKHOUSE_ADMIN_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_clickhouse_ingestor_password=${{ secrets.CLICKHOUSE_INGESTOR_PASSWORD }}" >> $GITHUB_ENV

      - name: Terraform Format
        run: terraform fmt -recursive -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
